version: '3.8'
services:
  server:
    build: ./tests/server
    cap_add:
      - NET_ADMIN  # Allows modification of network settings like iptables
    volumes:
      - ./iptables-rules.sh:/iptables-rules.sh
    networks:
      - testnet
    command: sh -c "/iptables-rules.sh && tail -f /dev/null"

  client:
    build: ./tests/client
    depends_on:
      - server
    networks:
      - testnet
    command: tail -f /dev/null

networks:
  testnet:
